class Constants:
    APPLICATION_TITLE = "Welcome to Kafka Local Setup Tool"
    APPLICATION_WINDOW_TITLE = "Kafka Application Tool"
    START_BUTTON = "Start"
    STOP_BUTTON = "Stop"
    CHOOSE_FOLDER = "Choose Folder"
    SELECT_FOLDER = "Select the folder"
    ZOOKEEPER_START_SERVER_PATH = "bin/zookeeper-server-start.sh"
    APACHE_ZOOKEEPER_START_SERVER_CONFIG = "config/zookeeper.properties"
    CONFLUENT_ZOOKEEPER_START_SERVER_CONFIG = "etc/zookeeper.properties"
    KAFKA_START_SERVER_PATH = "bin/kafka-server-start.sh"
    APACHE_KAFKA_START_SERVER_CONFIG = "config/server.properties"
    CONFLUENT_KAFKA_START_SERVER_CONFIG = "etc/server.properties"
    ZOOKEEPER_STOP_SERVER_PATH = "bin/zookeeper-server-stop.sh"
    KAFKA_STOP_SERVER_PATH = "bin/kafka-server-stop.sh"
    KAFKA_BASE_IMAGE = "app/images/kafka.png"
    APACHE_KAFKA = "Apache"
    CONFLUENT_KAFKA = "Confluent"
